services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/nginx/Docker-tomi/app/certs:/etc/nginx/certs:ro
      - /home/nginx/Docker-tomi/app/vhostd:/etc/nginx/vhost.d
      - /home/nginx/Docker-tomi/app/html:/usr/share/nginx/html
      - /home/nginx/Docker-tomi/app/acme:/etc/acme.sh
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /home/nginx/Docker-tomi/app/certs:/etc/nginx/certs:rw
      - /home/nginx/Docker-tomi/app/vhostd:/etc/nginx/vhost.d
      - /home/nginx/Docker-tomi/app/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/nginx/Docker-tomi/app/acme:/etc/acme.sh

  www:
    image: nginx:alpine3.21
    restart: always
    expose:
      - "80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=tomi.ddns.net
      - LETSENCRYPT_HOST=tomi.ddns.net
      - LETSENCRYPT_EMAIL=tomasgump6@gmail.com
    depends_on:
      - nginx-proxy
      - letsencrypt

volumes:
  certs:
  html:
  vhostd:
  acme:
